name: on-merge-workflow
on:
  push:
    branches: [master]
jobs:
  test:
    runs-on: # [to be filled]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install Node.js
        run: npm i && npm run test
  build-deploy:
    runs-on: # [to be filled]
    steps:
    - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 #
        with:
          heroku_api_key: ${{secrets.34d500af-6f93-484e-a778-7dc8ed524a80}}
          heroku_app_name: "workshop-18-yb" #Must be unique in Heroku
          heroku_email: "yuvalbader96@gmail.com"